export const en = {
  site: {
    name: "Leme",
    tagline: "Upload AI-generated HTML and share with a link",
    description:
      "Upload AI-generated HTML files and share them with anyone through a link. Collaborate with comments, suggestions, and forks.",
  },
  nav: {
    plans: "Plans",
    blog: "Blog",
    myFiles: "My files",
    newUpload: "New upload",
    signIn: "Sign in",
    signOut: "Sign out",
  },
  home: {
    heroBadge: "AI-generated HTML, made shareable",
    heroTitle: "Turn what you build with AI into pages anyone can open",
    heroDescription:
      "Upload the HTML your favorite AI tool generated, get a shareable link in seconds, and let people comment, suggest changes, or fork it into something new.",
    ctaUpload: "Upload your HTML",
    ctaPlans: "See plans",
    heroNote: "No account needed to try it — pages you upload without signing in stay saved in this browser.",
    featureUpload: "Upload",
    featureUploadDesc: "Drop in any .html file up to 2MB — no build step, no config.",
    featureShare: "Share",
    featureShareDesc: "Every upload gets its own page and link, ready to send.",
    featureCollaborate: "Collaborate",
    featureCollaborateDesc: "Visitors can comment, suggest changes, or fork your page.",
    featureControl: "Stay in control",
    featureControlDesc: "Free plan has limits and a watermark; Pro removes both.",
    howTitle: "How it works",
    howSubtitle: "From AI prompt to public link in four steps.",
    step1: "Generate",
    step1Desc: "Ask ChatGPT, Claude, Gemini, or any AI assistant for a single HTML file.",
    step2: "Save",
    step2Desc: "Copy the HTML code and save it as a .html file on your computer.",
    step3: "Upload",
    step3Desc: "Drop the file into Leme and add a title and description.",
    step4: "Share",
    step4Desc: "Get a public link like leme.app/p/xyz and share it anywhere.",
    toolsTitle: "Works with your favorite AI tools",
    toolsSubtitle: "Upload HTML generated by the most popular AI coding assistants and app builders.",
    finalTitle: "Ready to share what you built?",
    finalSubtitle: "It takes less than a minute — no sign-up required to get started.",
  },
  footer: {
    product: "Product",
    resources: "Resources",
    social: "Social",
    features: "Features",
    pricing: "Pricing",
    useCases: "Use cases",
    about: "About",
    blog: "Blog",
    faq: "FAQ",
    terms: "Terms",
    privacy: "Privacy",
    contact: "Contact",
    rights: "All rights reserved.",
    madeFor: "Made for AI-generated HTML.",
  },
  pricing: {
    title: "Simple plans, no catch",
    subtitle:
      "Use it without creating an account to try it quickly, create a free account to keep more pages, or go Pro when you want to keep everything live with no limit.",
    noAccount: {
      name: "No account",
      price: "$0",
      description: "To try it out quickly, no sign-up.",
      features: {
        pages: "{count} active page at a time",
        expires: "Expires in {days} days",
        watermark: "With watermark",
      },
      cta: "Use now",
    },
    free: {
      name: "Free",
      price: "$0",
      description: "Create an account and get more space.",
      features: {
        pages: "{count} active pages at the same time",
        expires: "Expires in {days} days",
        watermark: "With watermark",
      },
      cta: "Create free account",
    },
    pro: {
      name: "Pro",
      description: "For those who want to keep pages live with no limit.",
      monthly: "Monthly",
      yearly: "Yearly",
      priceUnitMonth: "month",
      priceUnitYear: "year",
      yearlySavings: "2 months free vs. paying monthly",
      features: ["Unlimited active pages", "Never expires", "No watermark"],
      cta: "Upgrade to Pro",
      ctaLoading: "Redirecting...",
    },
    footerNote: "Payments are processed securely by Stripe. Cancel anytime from your billing settings.",
  },
  common: {
    expiration: {
      expired: "expired",
      oneDay: "expires in 1 day",
      days: "expires in {count} days",
    },
  },
  about: {
    metadataDescription:
      "Learn about Leme: a simple way to upload AI-generated HTML pages and share them with a link.",
    title: "About Leme",
    intro:
      "Leme was built for everyone who creates HTML with AI and needs a fast, reliable way to share the result. No hosting setup, no build pipeline — just upload your file and get a link you can send to anyone.",
    whyTitle: "Why we built it",
    whyText:
      "AI tools can generate complete HTML pages in seconds, but publishing them is still harder than it should be. We wanted a place where you could drop a file, grab a link, and move on.",
    whatTitle: "What you can do",
    whatItems: [
      "Upload single HTML files up to your plan limit",
      "Get a public page and shareable link instantly",
      "Receive comments, suggestions, and forks from visitors",
      "Upgrade to Pro for unlimited pages and no watermark",
    ],
    cta: "See plans",
  },
  features: {
    metadataDescription:
      "Discover Leme features: upload HTML, share links, collaborate with comments, suggestions, and forks.",
    title: "Features",
    subtitle: "Everything you need to publish and share HTML pages generated by AI.",
    items: [
      {
        title: "Instant upload",
        description: "Drag or select an HTML file and get a public link in seconds.",
      },
      {
        title: "Shareable pages",
        description: "Every upload becomes a clean page with its own URL, ready to share anywhere.",
      },
      {
        title: "Collaboration",
        description: "Visitors can leave comments, suggestions, or fork your page into something new.",
      },
      {
        title: "No account required",
        description: "Try Leme without signing up. Create an account when you want to keep more pages.",
      },
      {
        title: "Pro plan",
        description: "Remove the watermark and keep unlimited pages live forever.",
      },
      {
        title: "Simple billing",
        description: "Upgrade or cancel anytime from your billing settings.",
      },
    ],
  },
  faq: {
    metadataDescription:
      "Frequently asked questions about Leme: upload AI-generated HTML, share links, collaborate, and manage plans.",
    metadataOpenGraphTitle: "Leme FAQ — Common questions answered",
    title: "Frequently Asked Questions",
    subtitle: "Everything you need to know about uploading, sharing, and collaborating with Leme.",
    stillQuestionsTitle: "Still have questions?",
    stillQuestionsText: "Send an email to",
    items: [
      {
        question: "What is Leme?",
        answer:
          "Leme is a fast way to upload AI-generated HTML files and publish them as shareable web pages. You get a public link instantly, and visitors can comment, suggest changes, or fork your page.",
      },
      {
        question: "How do I upload an HTML file?",
        answer:
          "Go to the upload page, drag or select your .html file, add a title and optional description, and click Upload. Leme hosts the file and gives you a public link in seconds.",
      },
      {
        question: "Do I need an account to use Leme?",
        answer:
          "No. You can upload without signing up. Anonymous uploads are saved in your browser, but they have stricter limits and expire after a few days. Creating a free account gives you more pages and longer retention.",
      },
      {
        question: "What AI tools work with Leme?",
        answer:
          "Any tool that exports a single .html file works. Popular options include ChatGPT, Claude, Gemini, v0, Lovable, Bolt, Replit, and hand-coded HTML from any code generator.",
      },
      {
        question: "What is the file size limit?",
        answer:
          "The current upload limit is 2 MB per file. This covers most AI-generated landing pages, portfolios, dashboards, and prototypes. If your file is larger, try compressing images or splitting the page.",
      },
      {
        question: "Can I share a page with someone else?",
        answer:
          "Yes. Every page gets a public link like leme.app/p/[id]. You can also create a dedicated share link from the sidebar, which is easier to copy and send.",
      },
      {
        question: "How does collaboration work?",
        answer:
          "Visitors with the link can open the sidebar and leave comments, suggestions, or forks. Forks create a new copy of the page that the contributor can edit and share back.",
      },
      {
        question: "What happens when a page expires?",
        answer:
          "Free and anonymous pages expire after their plan retention period. Once expired, the page is no longer viewable. Pro pages never expire as long as the subscription is active.",
      },
      {
        question: "What is the difference between Free and Pro?",
        answer:
          "The Free plan lets you keep a small number of active pages with a Leme watermark. The Pro plan removes the watermark, removes the active-page limit, and keeps pages live forever.",
      },
      {
        question: "How much does Pro cost?",
        answer:
          "Leme Pro costs $9 per month or $90 per year. The yearly plan saves the equivalent of two months compared to paying monthly.",
      },
      {
        question: "Can I cancel Pro anytime?",
        answer:
          "Yes. You can cancel from the billing page at any time. Your Pro benefits stay active until the end of the current billing period.",
      },
      {
        question: "Is my uploaded content public?",
        answer:
          "Pages uploaded to Leme are public by default through their shareable links. Anyone with the link can view the page. Do not upload sensitive, private, or confidential content.",
      },
      {
        question: "Can I delete a page?",
        answer:
          "Yes. If you created the page while signed in, you can delete it from your dashboard. Anonymous pages are tied to your browser and can be removed from the My uploads page.",
      },
      {
        question: "Does Leme work on mobile?",
        answer:
          "Yes. The Leme site is responsive. You can upload, view, and share pages from any modern browser on desktop, tablet, or mobile.",
      },
      {
        question: "Can I use my own domain?",
        answer:
          "Not yet. Today every page is hosted under leme.app. Custom domains are on the roadmap for a future release.",
      },
      {
        question: "Does Leme support CSS, JavaScript, and images inside the HTML?",
        answer:
          "Yes. A single .html file that includes inline CSS, JavaScript, and base64 images will render correctly. External assets linked by URL may load depending on CORS and availability.",
      },
      {
        question: "How do I report abuse or copyrighted content?",
        answer:
          "Send an email to hello@leme-app.com with the page link and a description. We review reports and take action against content that violates our Terms of Service.",
      },
      {
        question: "Is there a public API?",
        answer: "No. Leme is designed for manual uploads through the web interface. API access is not available.",
      },
      {
        question: "Who built Leme?",
        answer:
          "Leme was built by a small team focused on making AI-generated HTML easy to publish and share. We are independent, bootstrapped, and customer-funded through Pro subscriptions.",
      },
      {
        question: "How do I get in touch?",
        answer: "Email us at hello@leme-app.com or reach out through Twitter / X and LinkedIn.",
      },
    ],
  },
  aiLanding: {
    worksWith: "Works with {toolName}",
    howItWorks: "How it works",
    commonUseCases: "Common use cases",
    readyToPublish: "Ready to publish your {toolName} HTML?",
    ctaUpload: "Upload your HTML",
    noAccount: "Upload your file and get a public link in seconds. No account required to try.",
    whyUseLeme: "Why use Leme with {toolName}?",
    whyPoints: [
      "Get a public link without leaving your browser.",
      "Share the page with anyone, even if they do not have {toolName} access.",
      "Collect feedback, suggestions, and forks from reviewers.",
      "Keep pages live forever with Leme Pro.",
    ],
  },
  aiTools: {
    chatgpt: {
      metadataTitle: "Host and share HTML from ChatGPT",
      metadataDescription:
        "Upload HTML generated by ChatGPT to Leme and get a public shareable link in seconds. No hosting setup required.",
      ogTitle: "Host HTML from ChatGPT — Leme",
      ogDescription: "Upload ChatGPT-generated HTML and share it with a public link.",
      headline: "Host and share HTML from ChatGPT",
      description:
        "ChatGPT can write complete landing pages, portfolios, and prototypes in a single HTML file. Upload that file to Leme and get a public link you can share anywhere.",
      useCases: ["ChatGPT landing pages", "ChatGPT portfolios", "ChatGPT prototypes", "ChatGPT one-page sites"],
      steps: [
        "Ask ChatGPT to generate a complete, single-file HTML page with inline CSS. For example: 'Create a responsive landing page for a SaaS product in one HTML file.'",
        "Copy the full HTML response and save it as page.html on your computer.",
        "Open Leme, drag the file into the upload form, and add a title and optional description.",
        "Click Upload. Leme hosts the page and gives you a public link like leme.app/p/xyz.",
        "Share the link with teammates, clients, or on social media. Visitors can also leave comments and suggestions.",
      ],
      schemaName: "How to publish HTML from ChatGPT with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by ChatGPT to Leme and getting a public shareable link.",
    },
    bolt: {
      metadataTitle: "Host and share HTML from Bolt",
      metadataDescription:
        "Upload HTML generated by Bolt to Leme and get a public shareable link in seconds. Share Bolt prototypes and one-page sites without a full deployment.",
      ogTitle: "Host HTML from Bolt — Leme",
      ogDescription: "Upload Bolt-generated HTML and share it with a public link.",
      headline: "Host and share HTML from Bolt",
      description:
        "Bolt creates full-stack apps from prompts. Export a single HTML page or snapshot from your Bolt project and upload it to Leme to share a live preview instantly.",
      useCases: ["Bolt app previews", "Bolt landing pages", "Bolt prototypes", "Bolt shareable demos"],
      steps: [
        "Generate a page or app in Bolt. Pick a single screen or landing page that can be exported as a standalone HTML file.",
        "Copy or export the HTML source and save it as page.html. Make sure styles and scripts are inline so the file works on its own.",
        "Upload the file to Leme and add a title and description.",
        "Click Upload to get a public link like leme.app/p/xyz.",
        "Share the link with stakeholders. They can review, comment, suggest, or fork the page.",
      ],
      schemaName: "How to publish HTML from Bolt with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by Bolt to Leme and getting a public shareable link.",
    },
    claude: {
      metadataTitle: "Host and share HTML from Claude",
      metadataDescription:
        "Upload HTML generated by Claude to Leme and get a public shareable link in seconds. Perfect for Claude Artifacts and prototypes.",
      ogTitle: "Host HTML from Claude — Leme",
      ogDescription: "Upload Claude-generated HTML and share it with a public link.",
      headline: "Host and share HTML from Claude",
      description:
        "Claude, including Claude Artifacts, can generate polished HTML pages and components. Upload them to Leme to make them public and shareable without any deployment.",
      useCases: ["Claude Artifacts hosting", "Claude prototypes", "Claude landing pages", "Claude component demos"],
      steps: [
        "Generate a page or artifact in Claude. Ask for a single self-contained HTML file with inline CSS and JavaScript.",
        "Switch to the code view in the Claude Artifact panel and copy the complete HTML source.",
        "Save the code as page.html on your computer.",
        "Upload the file to Leme, add a title, and click Upload.",
        "Copy the public link and share it. Reviewers can leave comments, suggestions, or forks in the sidebar.",
      ],
      schemaName: "How to publish HTML from Claude with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by Claude or Claude Artifacts to Leme and getting a public shareable link.",
    },
    gemini: {
      metadataTitle: "Host and share HTML from Gemini",
      metadataDescription:
        "Upload HTML generated by Google Gemini to Leme and get a public shareable link in seconds. No hosting or build step required.",
      ogTitle: "Host HTML from Gemini — Leme",
      ogDescription: "Upload Gemini-generated HTML and share it with a public link.",
      headline: "Host and share HTML from Gemini",
      description:
        "Gemini can generate HTML pages, components, and small web apps. Upload the generated HTML file to Leme and publish it as a live page with a shareable link.",
      useCases: ["Gemini landing pages", "Gemini prototypes", "Gemini dashboards", "Gemini one-page sites"],
      steps: [
        "Ask Gemini to create a complete, single-file HTML page. For example: 'Build a responsive portfolio page in one HTML file with inline CSS.'",
        "Copy the generated HTML and save it as page.html.",
        "Open Leme and upload the file. Add a title and optional description so visitors understand the page.",
        "Click Upload and get a public link like leme.app/p/xyz.",
        "Share the link. The sidebar lets visitors collaborate with comments, suggestions, and forks.",
      ],
      schemaName: "How to publish HTML from Gemini with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by Google Gemini to Leme and getting a public shareable link.",
    },
    lovable: {
      metadataTitle: "Host and share HTML from Lovable",
      metadataDescription:
        "Upload HTML generated by Lovable to Leme and get a public shareable link in seconds. Publish Lovable apps as standalone pages.",
      ogTitle: "Host HTML from Lovable — Leme",
      ogDescription: "Upload Lovable-generated HTML and share it with a public link.",
      headline: "Host and share HTML from Lovable",
      description:
        "Lovable builds full-stack apps and pages. Export a single HTML snapshot from your Lovable project and upload it to Leme for a quick public preview.",
      useCases: ["Lovable app previews", "Lovable landing pages", "Lovable prototypes", "Lovable shareable demos"],
      steps: [
        "Generate a page or app in Lovable. Focus on a single screen or a landing page that works as a standalone HTML file.",
        "Export or copy the HTML source and save it as page.html. Inline CSS and JavaScript so the file works on its own.",
        "Upload the file to Leme and fill in the title and description.",
        "Click Upload to get a public link.",
        "Share the link with reviewers. They can leave comments and suggestions without needing Lovable access.",
      ],
      schemaName: "How to publish HTML from Lovable with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by Lovable to Leme and getting a public shareable link.",
    },
    v0: {
      metadataTitle: "Host and share HTML from v0",
      metadataDescription:
        "Upload HTML generated by v0 to Leme and get a public shareable link in seconds. Share your v0 prototypes without deploying a full project.",
      ogTitle: "Host HTML from v0 — Leme",
      ogDescription: "Upload v0-generated HTML and share it with a public link.",
      headline: "Host and share HTML from v0",
      description:
        "v0 generates beautiful React and HTML components. Export a single HTML file from v0 and upload it to Leme to share a live preview with anyone.",
      useCases: ["v0 component previews", "v0 landing pages", "v0 prototypes", "v0 UI demos"],
      steps: [
        "Generate a UI or page in v0. Ask for a single self-contained HTML file, or export the generated code and wrap it into one HTML file.",
        "Copy the HTML source and save it as page.html.",
        "Upload the file to Leme and add a clear title and description.",
        "Click Upload to get a public link.",
        "Share the link and collect feedback through comments, suggestions, and forks.",
      ],
      schemaName: "How to publish HTML from v0 with Leme",
      schemaDescription:
        "Step-by-step guide to uploading HTML generated by v0 to Leme and getting a public shareable link.",
    },
  },
  useCases: {
    metadataDescription:
      "Discover how teams and creators use Leme to publish and share AI-generated HTML pages for landing pages, portfolios, prototypes, dashboards, and more.",
    metadataOpenGraphTitle: "Leme Use Cases — Publish AI-generated HTML for any project",
    title: "What can you publish with Leme?",
    subtitle: "Any AI-generated HTML file becomes a live, shareable page. Here are the most common ways people use Leme.",
    ctaTitle: "Have an HTML file ready?",
    ctaSubtitle: "Upload it now and get a shareable link in seconds.",
    ctaButton: "Upload your HTML",
    items: [
      {
        title: "Landing pages",
        description:
          "Generate a complete marketing landing page with an AI coding assistant, then upload it to Leme and share the link with your team, clients, or stakeholders in seconds.",
        keywords: ["AI landing page", "share landing page", "host HTML landing page"],
      },
      {
        title: "Portfolios",
        description:
          "Turn a single HTML file from a design experiment or personal project into a live portfolio piece. Perfect for designers, developers, and students who want a quick public demo.",
        keywords: ["AI portfolio", "share portfolio HTML", "host portfolio online"],
      },
      {
        title: "Prototypes and MVPs",
        description:
          "Build an interactive prototype with AI, publish it on Leme, and collect feedback through comments and suggestions without setting up a full deployment pipeline.",
        keywords: ["AI prototype", "HTML prototype hosting", "share MVP"],
      },
      {
        title: "Dashboards",
        description:
          "Publish AI-generated dashboard HTML with charts and tables so teammates can preview the layout and interaction without needing a backend or database connected.",
        keywords: ["AI dashboard", "HTML dashboard hosting", "share dashboard"],
      },
      {
        title: "Newsletters and one-pagers",
        description:
          "Create a beautiful one-page email or announcement with AI, host it on Leme, and share the link in your newsletter, social media, or chat.",
        keywords: ["AI one-pager", "HTML newsletter hosting", "share one-page site"],
      },
      {
        title: "Forms and micro-apps",
        description:
          "Upload small HTML forms, calculators, or interactive widgets generated by AI and share them with a direct link. Ideal for quick experiments and user tests.",
        keywords: ["AI form hosting", "HTML micro-app", "share HTML form"],
      },
      {
        title: "Documentation and demos",
        description:
          "Publish technical documentation pages, component demos, or style guides generated from AI prompts so your team has a live reference to review and discuss.",
        keywords: ["AI documentation", "HTML demo hosting", "share documentation"],
      },
      {
        title: "Event and campaign pages",
        description:
          "Generate a seasonal campaign or event page with AI and publish it instantly. Update by forking the page and sharing the new version.",
        keywords: ["AI campaign page", "event page hosting", "share campaign HTML"],
      },
    ],
  },
  dashboard: {
    title: "My dashboard",
    newUpload: "+ New upload",
    activePages: "{active}/{max} active pages",
    activePagesUnlimited: "{active} active page(s) · no limit",
    renewsOn: "Renews on {date}",
    cancelsAtPeriodEnd: " · cancels at period end",
    yearly: " · yearly",
    monthly: " · monthly",
    limitReachedUpgrade: "Limit reached — upgrade",
    viewProPlan: "View Pro plan",
    billingSettings: "Billing settings",
    emptyState: "You haven't uploaded any HTML yet.",
    emptyStateLink: "Make your first upload",
    views: "{count} views",
    uploadedOn: "uploaded on {date}",
  },
  mine: {
    title: "My uploads",
    newUpload: "+ New upload",
    activePagesInBrowser: "{active}/{max} active page(s) in this browser",
    noAccount: "No account",
    createAccountForSpace: "Create a free account for more space",
    emptyState: "No uploads saved in this browser yet.",
    emptyStateLink: "Upload your first HTML",
    browserListWarning:
      "This list is saved in this browser — if you clear the site's data or switch devices, it's gone.",
    createAccountLink: "Create an account",
    dontLoseUploads: "so you don't lose your uploads.",
    views: "{count} views",
    uploadedOn: "uploaded on {date}",
  },
  blog: {
    title: "Leme Blog",
    subtitle: "Tips, tutorials, and updates on publishing and sharing AI-generated HTML.",
    readMore: "Read more \u2192",
    posts: [
      {
        slug: "how-to-publish-html-from-ai",
        title: "How to publish HTML from ChatGPT, Claude, and Gemini",
        excerpt:
          "A step-by-step guide to exporting HTML from popular AI coding assistants and publishing it online with a shareable link.",
        date: "2026-08-16",
      },
      {
        slug: "share-ai-landing-page-in-30-seconds",
        title: "How to share an AI-generated landing page in 30 seconds",
        excerpt:
          "Turn a prompt into a live landing page. Upload the HTML to Leme and send the link to anyone.",
        date: "2026-08-16",
      },
      {
        slug: "collect-feedback-on-html-prototypes",
        title: "The best way to collect feedback on HTML prototypes",
        excerpt:
          "Why comments, suggestions, and forks make Leme a lightweight feedback tool for AI-generated prototypes.",
        date: "2026-08-16",
      },
    ],
  },
  blogPosts: {
    howToPublish: {
      metadataTitle: "How to publish HTML from ChatGPT, Claude, and Gemini",
      metadataDescription:
        "Learn how to export HTML from ChatGPT, Claude, Gemini, and other AI coding assistants and publish it online with Leme.",
      ogTitle: "How to publish HTML from ChatGPT, Claude, and Gemini",
      ogDescription: "Step-by-step guide to exporting AI-generated HTML and sharing it with a public link.",
      title: "How to publish HTML from ChatGPT, Claude, and Gemini",
      subtitle:
        "A step-by-step guide to exporting HTML from popular AI coding assistants and publishing it online with a shareable link.",
      ctaTitle: "Try it now",
      ctaSubtitle: "Upload an HTML file and get a shareable link in seconds.",
      sections: [
        {
          type: "paragraph",
          content:
            "AI coding assistants can generate complete HTML pages in seconds. The problem is sharing them. Most people paste code into a local file, open it in a browser, and send a screenshot. That works for a quick look, but it is not a real shareable link.",
        },
        { type: "heading", content: "The easiest workflow" },
        {
          type: "list",
          items: [
            "Ask the AI for a single-file HTML page. For example: 'Create a landing page for a coffee shop in a single HTML file with inline CSS.'",
            "Copy the generated HTML code.",
            "Save it as page.html on your computer.",
            "Go to Leme upload and select the file.",
            "Add a title and optional description.",
            "Click Upload. You get a public link like leme.app/p/xyz.",
          ],
        },
        { type: "heading", content: "ChatGPT" },
        {
          type: "paragraph",
          content:
            "In ChatGPT, ask for a complete HTML file. If the output is too long, ask it to continue. Once you have the full code, save it as .html and upload to Leme. ChatGPT Code Interpreter can also generate HTML files directly if you ask it to write and export the file.",
        },
        { type: "heading", content: "Claude" },
        {
          type: "paragraph",
          content:
            "Claude Artifacts can render HTML and React components. When Claude shows an artifact, click the code view, copy the HTML, and save it. Leme will host that exact HTML and make it shareable with anyone.",
        },
        { type: "heading", content: "Gemini" },
        {
          type: "paragraph",
          content:
            "Gemini can generate HTML snippets in its response. Ask for a single, self-contained HTML file with inline styles. Copy the result, save it, and upload to Leme.",
        },
        { type: "heading", content: "Other tools" },
        {
          type: "paragraph",
          content:
            "The same workflow works for v0, Lovable, Bolt, Replit Agent, and any other tool that produces a single HTML file. If the tool exports a ZIP or multiple files, first combine the CSS and JavaScript into the HTML file, then upload.",
        },
        { type: "heading", content: "What makes Leme useful" },
        {
          type: "list",
          items: [
            "No hosting setup.",
            "Instant public link.",
            "Works on desktop and mobile.",
            "Visitors can leave comments and suggestions.",
            "Free to try; Pro for unlimited pages and no watermark.",
          ],
        },
      ],
    },
    shareLandingPage: {
      metadataTitle: "How to share an AI-generated landing page in 30 seconds",
      metadataDescription:
        "Turn a prompt into a live landing page. Upload the AI-generated HTML to Leme and send the link to anyone.",
      ogTitle: "How to share an AI-generated landing page in 30 seconds",
      ogDescription: "From prompt to public link in under a minute using Leme.",
      title: "How to share an AI-generated landing page in 30 seconds",
      subtitle: "From prompt to public link in under a minute. No deployment, no hosting account, no build step.",
      ctaTitle: "Create your landing page",
      ctaSubtitle: "Upload your AI-generated HTML and get a link in seconds.",
      sections: [
        {
          type: "paragraph",
          content:
            "Landing pages are one of the best use cases for AI coding assistants. You describe your product, the AI writes the copy, picks colors, and builds a responsive layout. The only missing piece is a public URL.",
        },
        { type: "heading", content: "The 30-second workflow" },
        {
          type: "list",
          items: [
            "Prompt the AI: 'Create a responsive landing page for a SaaS that helps people share AI-generated HTML. Single HTML file, inline CSS, modern design.'",
            "Save the response as landing.html.",
            "Open Leme upload.",
            "Drop the file, add a title, and click Upload.",
            "Copy the public link and share it.",
          ],
        },
        { type: "heading", content: "Why this beats other options" },
        {
          type: "list",
          items: [
            "GitHub Pages requires a repository and a commit.",
            "Netlify Drop is great for folders, but overkill for a single file.",
            "Vercel is built for frameworks, not plain HTML files.",
            "Leme is built exactly for this: one HTML file, one public link.",
          ],
        },
        { type: "heading", content: "Share with context" },
        {
          type: "paragraph",
          content:
            "When you share a Leme link, visitors can open the sidebar to see the page title, description, and even leave comments. This makes it perfect for early feedback, client reviews, and team collaboration.",
        },
        { type: "heading", content: "Keep it live forever" },
        {
          type: "paragraph",
          content:
            "Free and anonymous pages expire after a while. If you want a landing page that stays live without watermarks, upgrade to Leme Pro for unlimited pages and permanent hosting.",
        },
      ],
    },
    collectFeedback: {
      metadataTitle: "The best way to collect feedback on HTML prototypes",
      metadataDescription:
        "Why comments, suggestions, and forks make Leme a lightweight feedback tool for AI-generated HTML prototypes.",
      ogTitle: "The best way to collect feedback on HTML prototypes",
      ogDescription: "Collect comments, suggestions, and forks on AI-generated HTML prototypes with Leme.",
      title: "The best way to collect feedback on HTML prototypes",
      subtitle:
        "Why comments, suggestions, and forks make Leme a lightweight feedback tool for AI-generated prototypes.",
      ctaTitle: "Start collecting feedback",
      ctaSubtitle: "Upload your prototype and share it with your team.",
      sections: [
        {
          type: "paragraph",
          content:
            "Prototypes are meant to be reviewed. But when you share an HTML file over email or Slack, you get vague feedback like 'looks good' or 'change the blue.' Leme turns a static file into a collaborative review surface.",
        },
        { type: "heading", content: "Three types of feedback" },
        {
          type: "list",
          items: [
            "Comments: General thoughts and reactions about the whole page or a specific idea.",
            "Suggestions: Concrete change proposals, like 'make the headline larger' or 'add a pricing section.'",
            "Forks: A contributor can create a copy of the page, edit it, and share the new version back. This is the closest thing to a pull request for an AI-generated page.",
          ],
        },
        { type: "heading", content: "How to use it" },
        {
          type: "list",
          items: [
            "Generate your prototype with an AI assistant.",
            "Upload it to Leme.",
            "Share the link with reviewers.",
            "Reviewers open the sidebar and add comments or suggestions.",
            "For bigger changes, ask a reviewer to fork the page and iterate.",
          ],
        },
        { type: "heading", content: "When to use Leme instead of Figma or GitHub" },
        {
          type: "paragraph",
          content:
            "Figma is great for design, and GitHub is great for code. Leme sits in the middle: the page is already live HTML, but you still need quick feedback before committing to a full deployment. It is ideal for side projects, client previews, and one-off experiments generated by AI.",
        },
        { type: "heading", content: "Keep a record" },
        {
          type: "paragraph",
          content:
            "Because every page has its own URL, you can share version A, then version B, then version C. Each link is a snapshot. Reviewers can compare them easily, and you can keep the best one as your final version.",
        },
      ],
    },
  },
  terms: {
    metadataTitle: "Terms of Service",
    metadataDescription: "Terms of service for using Leme.",
    title: "Terms of Service",
    lastUpdated: "Last updated: August 2026",
    sections: [
      {
        title: "1. Acceptance of Terms",
        paragraphs: [
          "By accessing or using Leme, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
        ],
      },
      {
        title: "2. Description of Service",
        paragraphs: [
          "Leme is a platform that allows users to upload HTML files, generate shareable links, and collaborate through comments, suggestions, and forks.",
        ],
      },
      {
        title: "3. User Content",
        paragraphs: [
          "You retain ownership of any content you upload. By uploading content, you grant Leme a limited license to host, display, and share that content as necessary to provide the service.",
          "You are solely responsible for the content you upload. Do not upload content that is illegal, harmful, infringing, or violates the rights of others.",
        ],
      },
      {
        title: "4. Prohibited Uses",
        paragraphs: [
          "You may not use Leme to distribute malware, phishing pages, spam, or any content that violates applicable laws or regulations.",
        ],
      },
      {
        title: "5. Paid Subscriptions",
        paragraphs: [
          "Leme offers free and paid plans. Paid subscriptions are billed through Stripe and can be cancelled at any time from your billing settings.",
        ],
      },
      {
        title: "6. Termination",
        paragraphs: [
          "We reserve the right to suspend or terminate accounts that violate these terms or abuse the service.",
        ],
      },
      {
        title: "7. Changes to Terms",
        paragraphs: [
          "We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.",
        ],
      },
      {
        title: "8. Contact",
        paragraphs: [
          "For questions about these terms, please contact us through our contact page.",
        ],
      },
    ],
  },
  privacy: {
    metadataTitle: "Privacy Policy",
    metadataDescription: "Privacy policy for Leme users.",
    title: "Privacy Policy",
    lastUpdated: "Last updated: August 2026",
    sections: [
      {
        title: "1. Information We Collect",
        paragraphs: [
          "When you use Leme, we may collect information you provide directly, such as your email address when you sign in, and anonymous identifiers when you upload without an account.",
        ],
      },
      {
        title: "2. Uploaded Content",
        paragraphs: [
          "HTML files you upload are stored securely so we can serve them through shareable links. We do not scan or use the content of your uploads for advertising purposes.",
        ],
      },
      {
        title: "3. Authentication",
        paragraphs: [
          "Leme uses Firebase Authentication for sign-in. We store a unique user identifier and your email address when you authenticate.",
        ],
      },
      {
        title: "4. Payments",
        paragraphs: [
          "Payments are processed by Stripe. We do not store your payment card details. Stripe may collect information necessary to process payments under their own privacy policy.",
        ],
      },
      {
        title: "5. Cookies and Analytics",
        paragraphs: [
          "We use essential cookies to keep you signed in and to remember anonymous uploads in your browser. We do not use third-party advertising cookies.",
        ],
      },
      {
        title: "6. Data Retention",
        paragraphs: [
          "Uploaded pages are retained according to your plan. Free and anonymous pages expire after the plan retention period. Pro pages are kept while your subscription is active.",
        ],
      },
      {
        title: "7. Your Rights",
        paragraphs: [
          "You can delete your uploaded pages at any time. If you have questions about your data, contact us through our contact page.",
        ],
      },
      {
        title: "8. Changes to This Policy",
        paragraphs: [
          "We may update this privacy policy from time to time. Significant changes will be posted on this page.",
        ],
      },
    ],
  },
  login: {
    title: "Sign in",
    subtitle: "Access your account to manage your uploads and share links.",
    googleSignIn: "Sign in with Google",
    googleSignInLoading: "Opening Google...",
    or: "or",
    magicLink: "Magic link",
    emailAndPassword: "Email and password",
    emailLabel: "Email",
    emailPlaceholder: "you@email.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    sendMagicLink: "Send magic link",
    sending: "Sending...",
    signIn: "Sign in",
    createAccount: "Create account",
    pleaseWait: "Please wait...",
    noAccount: "Don't have an account? Create one now",
    hasAccount: "Already have an account? Sign in",
    magicLinkSent: "Magic link sent! Check your inbox to continue.",
  },
  auth: {
    codeErrorTitle: "We couldn't confirm your sign-in",
    codeErrorSubtitle:
      "The link may have expired or already been used. Please try signing in again.",
    codeErrorCta: "Back to sign in",
    callbackConfirming: "Confirming your sign-in...",
    callbackEmailPrompt: "Confirm your email to finish signing in",
    callbackError: "This link may have expired or already been used.",
  },
  uploadLanding: {
    title: "Upload your HTML",
    savedFile: "Your saved file",
    savedFiles: "Your saved files",
    noAccount: "No account? No problem — your upload stays saved in this browser, access it later at {link}.",
    myUploads: "My uploads",
  },
  uploadForm: {
    fileLabel: "HTML file (.html, up to 2MB)",
    titleLabel: "Title",
    titlePlaceholder: "E.g.: Landing page generated with GPT",
    descriptionLabel: "Description (optional)",
    descriptionPlaceholder: "Tell us a bit about this HTML...",
    uploading: "Uploading...",
    upload: "Upload",
    errors: {
      notHtml: "Select an .html file.",
      tooLarge: "The file must be at most 2MB.",
      noFile: "Choose an .html file to upload.",
      generic: "Connection error while uploading the file.",
    },
  },
  planUpsell: {
    usage: "{active}/{max} active pages used.",
    atLimit: "You've reached your limit of {max} active page(s).",
    description: "Pro removes the limit, drops the watermark, and pages never expire.",
    cta: "Upgrade to Pro",
  },
  planLabels: {
    anonymous: "Anonymous",
    free: "Free",
    pro: "Pro",
  },
  expiredNotice: {
    title: "This page has expired",
    description:
      "The author's plan limits how long a page stays live. If you're the author, upgrade to the Pro plan to keep your pages from expiring.",
    cta: "Back to home",
  },
  uploadsMenu: {
    title: "Your uploads",
    empty: "You don't have any other uploads yet.",
    views: "{count} views",
    viewingNow: "viewing now",
    deleteLabel: "Delete upload",
    deleteConfirm: "Delete \"{title}\"? The page, its link, and its comments go away for good.",
    deleteError: "Could not delete the upload.",
    deleteTitle: "Delete this upload?",
    deleteCta: "Delete",
    cancel: "Cancel",
  },
  billing: {
    title: "Billing",
    subtitle: "Manage your plan, billing interval, and invoices.",
    subscription: {
      title: "Subscription",
      freePlan: "You are on the Free plan. Upgrade to Pro to keep pages live forever and remove the watermark.",
      viewPlans: "View plans",
      proTitle: "Pro plan",
      billedAnnually: "Billed annually",
      billedMonthly: "Billed monthly",
      statusActive: "Active",
      statusCancelsSoon: "Cancels soon",
      currentPeriodEnds: "Current period ends",
      billingInterval: "Billing interval",
      intervalYearly: "Yearly",
      intervalMonthly: "Monthly",
      cancelWarning:
        "Your Pro plan is scheduled to cancel at the end of the current billing period. You can resume it before then to keep the benefits.",
      syncing: "Syncing subscription details...",
    },
    invoices: {
      title: "Invoice history",
      loading: "Loading invoices...",
      error: "Could not load invoices.",
      empty: "No invoices yet.",
      invoice: "Invoice",
      view: "View",
      statusPaid: "paid",
    },
    actions: {
      manageBilling: "Manage billing",
      manageBillingLoading: "Opening...",
      cancelSubscription: "Cancel Pro plan",
      cancelling: "Cancelling...",
      cancelConfirm:
        "Are you sure you want to cancel your Pro plan? You will keep access until the end of the current billing period.",
      cancelConfirmTitle: "Cancel Pro plan?",
      cancelKeep: "Keep plan",
      cancelError: "Failed to cancel subscription.",
      upgradeToAnnual: "Upgrade to annual",
      upgrading: "Opening checkout...",
      upgradeError: "Failed to start upgrade.",
    },
  },
  pageViewer: {
    pageLink: "Page link",
    views: "{count} views",
    uploadedOn: "uploaded on {date}",
    sourceNote: "via shared link",
    reopenLabel: "Collaborate",
  },
  collapsibleSidebar: {
    show: "Show sidebar",
    hide: "Hide sidebar",
  },
  copyLink: {
    copy: "Copy",
    copied: "Copied!",
  },
  contributions: {
    typeComment: "Comment",
    typeSuggestion: "Suggestion",
    typeFork: "Fork",
    authorPlaceholder: "Your name (optional)",
    forkTitlePlaceholder: "Fork title",
    forkHtmlLabel: "Edit the HTML before creating the fork:",
    commentPlaceholder: "Leave a comment...",
    suggestionPlaceholder: "Describe your suggestion...",
    forkMessagePlaceholder: "Message about this fork (optional)",
    submit: "Submit",
    createFork: "Create fork",
    submitting: "Submitting...",
    emptyState: "No contributions yet. Be the first!",
    viewFork: "View fork →",
    error: "Connection error while submitting contribution.",
    forkOf: "Fork of {title}",
  },
  shareButton: {
    share: "Share",
    generating: "Generating...",
    error: "Connection error while generating the link.",
  },
  // Títulos/descrições de <head>. As rotas privadas (login, mine, dashboard,
  // billing, new) são noindex, então aqui o que importa é o título da aba;
  // já pageNotFound/untitledPage/viewPageDescription aparecem em /p e /s,
  // que são indexadas.
  meta: {
    loginTitle: "Sign in",
    loginDescription: "Sign in to Leme to manage your uploaded HTML pages and share links.",
    mineTitle: "My uploads",
    mineDescription: "View your anonymous uploads on Leme.",
    dashboardTitle: "Dashboard",
    dashboardDescription: "Manage your uploaded HTML pages and share links on Leme.",
    billingTitle: "Billing",
    billingDescription: "Manage your Leme Pro subscription, billing interval, and invoices.",
    newTitle: "Upload HTML",
    newDescription: "Upload an AI-generated HTML file to Leme and get a shareable link.",
    pageNotFound: "Page not found",
    sharedPageNotFound: "Shared page not found",
    untitledPage: "Shared page",
    viewPageDescription: "View {title} on Leme.",
  },
  pageSettings: {
    title: "Page settings",
    proOnly: "Pro",
    contributions: "Allow contributions",
    contributionsHint: "Visitors can comment, suggest changes, or fork this page.",
    branding: "Show Leme header",
    brandingHint: "The Leme bar stays visible above your page.",
    saving: "Saving...",
    error: "Could not save the settings.",
  },
  pageMemory: {
    title: "Shared memory",
    loading: "Loading shared memory...",
    error: "Could not load shared memory.",
    empty: "No data stored yet. Open this page and edit a field to see it here.",
    filterPlaceholder: "Filter keys or values...",
    exportCsv: "Export CSV",
  },
  newMemoryAlert: {
    message: "New data has been added to this page.",
    reload: "Reload",
    dismiss: "Dismiss",
  },
  authErrors: {
    invalidEmail: "That email address doesn't look valid.",
    userDisabled: "This account has been disabled.",
    userNotFound: "No account found with that email.",
    wrongPassword: "Incorrect email or password.",
    invalidCredential: "Incorrect email or password.",
    emailAlreadyInUse: "There's already an account with that email. Try signing in instead.",
    weakPassword: "Choose a password with at least 6 characters.",
    tooManyRequests: "Too many attempts. Wait a moment and try again.",
    networkRequestFailed: "Couldn't reach the server. Check your connection.",
    popupBlocked: "Your browser blocked the sign-in popup. Allow popups and try again.",
    unauthorizedDomain:
      "This domain isn't authorized in Firebase. Add it under Authentication > Settings > Authorized domains.",
    operationNotAllowed:
      "This sign-in method is disabled. Enable it under Authentication > Sign-in method in the Firebase console.",
    accountExistsWithDifferentCredential:
      "You already have an account with this email using a different sign-in method. Sign in that way first.",
    default: "Couldn't complete sign-in. Please try again.",
    connectionError: "Couldn't connect. Check your internet connection and try again.",
  },
};

export type Dictionary = typeof en;
