from __future__ import annotations

MAX_UPLOAD_SIZE_BYTES = 2 * 1024 * 1024
ALLOWED_UPLOAD_MIME_TYPES = frozenset({"text/html", "application/octet-stream"})

MAX_TITLE_LENGTH = 200
MAX_DESCRIPTION_LENGTH = 2000
MAX_AUTHOR_NAME_LENGTH = 100
MAX_CONTRIBUTION_CONTENT_LENGTH = 5000
MAX_FORK_HTML_LENGTH = MAX_UPLOAD_SIZE_BYTES
