import type { Metadata } from "next";
import Link from "next/link";
import {
  CollaborateIcon,
  ControlsIcon,
  ShareLinkIcon,
  UploadIcon,
} from "@/components/FeatureIcons";
import { type Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  const { lang } = await params;
  const locale = lang as Locale;
  const dict = await getDictionary(locale);
  return {
    title: dict.site.tagline,
    description: dict.site.description,
  };
}

export default async function HomePage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const locale = lang as Locale;
  const dict = await getDictionary(locale);

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to share AI-generated HTML with Leme",
    description:
      "A four-step guide to uploading HTML generated by AI tools such as ChatGPT, Claude, and Gemini to Leme and getting a public shareable link.",
    step: [
      {
        "@type": "HowToStep",
        position: 1,
        name: dict.home.step1,
        text: dict.home.step1Desc,
      },
      {
        "@type": "HowToStep",
        position: 2,
        name: dict.home.step2,
        text: dict.home.step2Desc,
      },
      {
        "@type": "HowToStep",
        position: 3,
        name: dict.home.step3,
        text: dict.home.step3Desc,
      },
      {
        "@type": "HowToStep",
        position: 4,
        name: dict.home.step4,
        text: dict.home.step4Desc,
      },
    ],
  };

  const tools = [
    { name: "ChatGPT", href: `/${locale}/chatgpt-html-hosting` },
    { name: "Claude", href: `/${locale}/claude-html-hosting` },
    { name: "Gemini", href: `/${locale}/gemini-html-hosting` },
    { name: "v0", href: `/${locale}/v0-html-hosting` },
    { name: "Lovable", href: `/${locale}/lovable-html-hosting` },
    { name: "Bolt", href: `/${locale}/bolt-html-hosting` },
  ];

  const features = [
    { title: dict.home.featureUpload, description: dict.home.featureUploadDesc, Icon: UploadIcon },
    { title: dict.home.featureShare, description: dict.home.featureShareDesc, Icon: ShareLinkIcon },
    {
      title: dict.home.featureCollaborate,
      description: dict.home.featureCollaborateDesc,
      Icon: CollaborateIcon,
    },
    {
      title: dict.home.featureControl,
      description: dict.home.featureControlDesc,
      Icon: ControlsIcon,
    },
  ];

  const steps = [
    { title: dict.home.step1, description: dict.home.step1Desc },
    { title: dict.home.step2, description: dict.home.step2Desc },
    { title: dict.home.step3, description: dict.home.step3Desc },
    { title: dict.home.step4, description: dict.home.step4Desc },
  ];

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />

      <div className="wrap pt-16 sm:pt-24">
        <p className="eyebrow">{dict.home.heroBadge}</p>
        <h1 className="display mt-6 max-w-[16ch]">{dict.home.heroTitle}</h1>
        <p className="lead mt-7">{dict.home.heroDescription}</p>

        <div className="mt-9 flex flex-wrap gap-3">
          <Link href={`/${locale}/new`} className="btn btn-primary btn-lg">
            {dict.home.ctaUpload}
          </Link>
          <Link href={`/${locale}/pricing`} className="btn btn-ghost btn-lg">
            {dict.home.ctaPlans}
          </Link>
        </div>

        <p className="mt-5 max-w-[52ch] text-xs text-mute-dim">{dict.home.heroNote}</p>

        <HeroVisual />
      </div>

      {/* Faixa de ferramentas: prova de compatibilidade logo abaixo do hero,
          onde a primeira pergunta de quem chega é "funciona com o que eu uso?" */}
      <div className="rule">
        <div className="wrap flex flex-wrap items-center justify-between gap-x-10 gap-y-5 py-7">
          <p className="text-[13px] text-mute-dim">{dict.home.toolsTitle}</p>
          <ul className="flex flex-wrap items-center gap-x-8 gap-y-3">
            {tools.map((tool) => (
              <li key={tool.name}>
                <Link
                  href={tool.href}
                  className="link-nav rounded-md text-sm tracking-[-0.01em]"
                >
                  {tool.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <section className="wrap py-24 sm:py-28">
        <div className="mb-16 grid items-end gap-x-16 gap-y-5 lg:grid-cols-[1.05fr_1fr]">
          <div>
            <p className="eyebrow">{dict.home.featureShare}</p>
            <h2 className="headline mt-5">{dict.site.tagline}</h2>
          </div>
          <p className="lead pb-1.5">{dict.home.toolsSubtitle}</p>
        </div>

        {/* Divisores em vez de cartões: as quatro capacidades são paralelas,
            não uma sequência — por isso não recebem numeração. */}
        <div className="grid grid-cols-1 gap-px border-y border-line-soft bg-line-soft sm:grid-cols-2 lg:grid-cols-4">
          {features.map(({ title, description, Icon }) => (
            <div key={title} className="bg-black px-7 py-9">
              <Icon className="h-6 w-6 text-brand-500" />
              <h3 className="subhead mt-6">{title}</h3>
              <p className="mt-2.5 text-[15px] text-mute">{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="wrap pb-24 sm:pb-28">
        <div className="panel px-7 py-14 sm:px-14">
          <p className="eyebrow">{dict.home.howTitle}</p>
          <h2 className="headline mt-5 max-w-[20ch]">{dict.home.howSubtitle}</h2>

          {/* Aqui a numeração carrega informação: é a ordem real do fluxo. */}
          <ol className="mt-14 grid grid-cols-1 gap-px overflow-hidden rounded-lg border border-line-soft bg-line-soft sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((step, index) => (
              <li key={step.title} className="bg-surface px-7 py-8">
                <span className="text-xs font-medium tracking-[0.14em] text-brand-500">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <h3 className="mt-5 text-lg font-medium tracking-[-0.02em]">{step.title}</h3>
                <p className="mt-2 text-[14.5px] text-mute">{step.description}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <div className="glow-cta rule py-28 text-center">
        <div className="wrap">
          <h2 className="headline mx-auto max-w-[18ch]">{dict.home.finalTitle}</h2>
          <p className="lead mx-auto mt-6">{dict.home.finalSubtitle}</p>
          <Link href={`/${locale}/new`} className="btn btn-primary btn-lg mt-9">
            {dict.home.ctaUpload}
          </Link>
        </div>
      </div>
    </>
  );
}

// O hero mostra a transformação que o produto faz: arquivos .html soltos
// viram páginas com link próprio. Os dois cartões são a tese da página.
function HeroVisual() {
  return (
    <div className="glow-hero relative mt-20 flex h-[300px] items-center justify-center overflow-hidden rounded-t-2xl border border-b-0 border-line-soft sm:h-[340px]">
      <FileCard
        name="landing-page.html"
        className="-rotate-6"
        widths={["w-full", "w-3/4", "w-1/2"]}
      />
      <FileCard
        name="dashboard-ui.html"
        className="mt-16 rotate-6"
        widths={["w-full", "w-2/3", "w-5/6"]}
      />
    </div>
  );
}

function FileCard({
  name,
  className,
  widths,
}: {
  name: string;
  className: string;
  widths: string[];
}) {
  return (
    <div
      className={`w-44 rounded-xl border border-line-soft bg-surface-2 p-3.5 shadow-[0_16px_40px_-12px_rgba(0,0,0,0.8)] ${className}`}
    >
      <div className="mb-3 flex gap-1.5">
        <span className="h-1.5 w-1.5 rounded-full bg-white/20" />
        <span className="h-1.5 w-1.5 rounded-full bg-white/20" />
        <span className="h-1.5 w-1.5 rounded-full bg-brand-500/60" />
      </div>
      <div className="space-y-1.5">
        {widths.map((width, index) => (
          <div key={index} className={`h-1.5 rounded-full bg-white/10 ${width}`} />
        ))}
      </div>
      <p className="mt-3 truncate text-[11px] text-mute-dim">{name}</p>
    </div>
  );
}
