import type { Metadata } from "next";
import Link from "next/link";
import {
  CollaborateIcon,
  ControlsIcon,
  ShareLinkIcon,
  UploadIcon,
} from "@/components/FeatureIcons";
import { type Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import type { Dictionary } from "@/lib/i18n/dictionaries/en";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  const { lang } = await params;
  const locale = lang as Locale;
  const dict = await getDictionary(locale);
  return {
    title: dict.site.tagline,
    description: dict.site.description,
  };
}

export default async function HomePage({
  params,
}: {
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const locale = lang as Locale;
  const dict = await getDictionary(locale);

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to share AI-generated HTML with Leme",
    description:
      "A four-step guide to uploading HTML generated by AI tools such as ChatGPT, Claude, and Gemini to Leme and getting a public shareable link.",
    step: [
      {
        "@type": "HowToStep",
        position: 1,
        name: dict.home.step1,
        text: dict.home.step1Desc,
      },
      {
        "@type": "HowToStep",
        position: 2,
        name: dict.home.step2,
        text: dict.home.step2Desc,
      },
      {
        "@type": "HowToStep",
        position: 3,
        name: dict.home.step3,
        text: dict.home.step3Desc,
      },
      {
        "@type": "HowToStep",
        position: 4,
        name: dict.home.step4,
        text: dict.home.step4Desc,
      },
    ],
  };

  const tools = [
    { name: "ChatGPT", href: `/${locale}/chatgpt-html-hosting` },
    { name: "Claude", href: `/${locale}/claude-html-hosting` },
    { name: "Gemini", href: `/${locale}/gemini-html-hosting` },
    { name: "v0", href: `/${locale}/v0-html-hosting` },
    { name: "Lovable", href: `/${locale}/lovable-html-hosting` },
    { name: "Bolt", href: `/${locale}/bolt-html-hosting` },
  ];

  const features = [
    {
      title: dict.home.featureUpload,
      description: dict.home.featureUploadDesc,
      Icon: UploadIcon,
    },
    {
      title: dict.home.featureShare,
      description: dict.home.featureShareDesc,
      Icon: ShareLinkIcon,
    },
    {
      title: dict.home.featureCollaborate,
      description: dict.home.featureCollaborateDesc,
      Icon: CollaborateIcon,
    },
    {
      title: dict.home.featureControl,
      description: dict.home.featureControlDesc,
      Icon: ControlsIcon,
    },
  ];

  const steps = [
    { title: dict.home.step1, description: dict.home.step1Desc },
    { title: dict.home.step2, description: dict.home.step2Desc },
    { title: dict.home.step3, description: dict.home.step3Desc },
    { title: dict.home.step4, description: dict.home.step4Desc },
  ];

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />

      <div className="wrap pt-16 sm:pt-24">
        <p className="eyebrow">{dict.home.heroBadge}</p>
        <h1 className="display mt-6 max-w-[16ch]">{dict.home.heroTitle}</h1>
        <p className="lead mt-7">{dict.home.heroDescription}</p>

        <div className="mt-9 flex flex-wrap gap-3">
          <Link href={`/${locale}/new`} className="btn btn-primary btn-lg">
            {dict.home.ctaUpload}
          </Link>
          <Link href={`/${locale}/pricing`} className="btn btn-ghost btn-lg">
            {dict.home.ctaPlans}
          </Link>
        </div>

        <p className="mt-5 max-w-[52ch] text-xs text-mute-dim">
          {dict.home.heroNote}
        </p>

        <HeroVisual dict={dict} />
      </div>

      {/* Faixa de ferramentas: prova de compatibilidade logo abaixo do hero,
          onde a primeira pergunta de quem chega é "funciona com o que eu uso?" */}
      <div className="rule">
        <div className="wrap flex flex-wrap items-center justify-between gap-x-10 gap-y-5 py-7">
          <p className="text-[13px] text-mute-dim">{dict.home.toolsTitle}</p>
          <ul className="flex flex-wrap items-center gap-x-8 gap-y-3">
            {tools.map((tool) => (
              <li key={tool.name}>
                <Link
                  href={tool.href}
                  className="link-nav rounded-md text-sm tracking-[-0.01em]"
                >
                  {tool.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <section className="wrap py-24 sm:py-28">
        <div className="mb-16 grid items-end gap-x-16 gap-y-5 lg:grid-cols-[1.05fr_1fr]">
          <div>
            <p className="eyebrow">{dict.home.featureShare}</p>
            <h2 className="headline mt-5">{dict.site.tagline}</h2>
          </div>
          <p className="lead pb-1.5">{dict.home.toolsSubtitle}</p>
        </div>

        {/* Divisores em vez de cartões: as quatro capacidades são paralelas,
            não uma sequência — por isso não recebem numeração. */}
        <div className="grid grid-cols-1 gap-px border-y border-line-soft bg-line-soft sm:grid-cols-2 lg:grid-cols-4">
          {features.map(({ title, description, Icon }) => (
            <div key={title} className="bg-black px-7 py-9">
              <Icon className="h-6 w-6 text-brand-500" />
              <h3 className="subhead mt-6">{title}</h3>
              <p className="mt-2.5 text-[15px] text-mute">{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="wrap pb-24 sm:pb-28">
        <div className="panel px-7 py-14 sm:px-14">
          <p className="eyebrow">{dict.home.howTitle}</p>
          <h2 className="headline mt-5 max-w-[20ch]">
            {dict.home.howSubtitle}
          </h2>

          {/* Aqui a numeração carrega informação: é a ordem real do fluxo. */}
          <ol className="mt-14 grid grid-cols-1 gap-px overflow-hidden rounded-lg border border-line-soft bg-line-soft sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((step, index) => (
              <li key={step.title} className="bg-surface px-7 py-8">
                <span className="text-xs font-medium tracking-[0.14em] text-brand-500">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <h3 className="mt-5 text-lg font-medium tracking-[-0.02em]">
                  {step.title}
                </h3>
                <p className="mt-2 text-[14.5px] text-mute">
                  {step.description}
                </p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <div className="glow-cta rule py-28 text-center">
        <div className="wrap">
          <h2 className="headline mx-auto max-w-[18ch]">
            {dict.home.finalTitle}
          </h2>
          <p className="lead mx-auto mt-6">{dict.home.finalSubtitle}</p>
          <Link href={`/${locale}/new`} className="btn btn-primary btn-lg mt-9">
            {dict.home.ctaUpload}
          </Link>
        </div>
      </div>
    </>
  );
}

function HeroVisual({ dict }: { dict: Dictionary }) {
  const avatars = [
    { tone: "bg-brand-500 text-black", label: "A", cls: "scene scene-avatar-1" },
    { tone: "bg-white/25 text-white", label: "M", cls: "scene scene-avatar-2" },
    { tone: "bg-white/15 text-mute", label: "+", cls: "scene scene-avatar-3" },
  ];

  return (
    <div className="glow-hero relative mt-20 flex h-[420px] items-center justify-center overflow-hidden rounded-t-2xl border border-b-0 border-line-soft sm:h-[520px]">
      <div className="relative w-[290px] sm:w-[560px]">
        <div className="scene scene-window relative w-full overflow-hidden rounded-xl border border-line bg-surface-2 shadow-[0_32px_80px_-20px_rgba(0,0,0,0.95)]">
          <div className="flex items-center gap-3 border-b border-line-soft px-4 py-3">
            <span className="flex shrink-0 gap-1.5">
              <span className="h-2 w-2 rounded-full bg-white/20" />
              <span className="h-2 w-2 rounded-full bg-white/20" />
              <span className="h-2 w-2 rounded-full bg-brand-500/70" />
            </span>
            <span className="flex min-w-0 flex-1 items-center gap-2 rounded-md bg-black/50 px-2.5 py-1.5">
              <ShareLinkIcon className="h-3 w-3 shrink-0 text-mute-dim" />
              <span className="scene scene-url block overflow-hidden whitespace-nowrap text-[11px] text-mute sm:text-xs">
                leme-app.com/p/a1b2c3
              </span>
            </span>
            <span className="scene scene-copy-btn shrink-0 rounded px-2 py-1 text-[10px] font-medium sm:text-[11px]">
              {dict.copyLink.copy}
            </span>
          </div>

          <div className="space-y-3 px-5 py-6 sm:px-7 sm:py-8">
            <div className="scene scene-line-1 h-3 w-1/2 rounded-full bg-white/25" />
            <div className="scene scene-line-2 h-2 w-full rounded-full bg-white/10" />
            <div className="scene scene-line-3 h-2 w-5/6 rounded-full bg-white/10" />
            <div className="scene scene-line-4 grid grid-cols-3 gap-2.5 pt-2">
              {["bg-white/[0.07]", "bg-white/[0.07]", "bg-brand-500/15"].map((tone, i) => (
                <div key={i} className={`h-12 rounded-lg sm:h-16 ${tone}`} />
              ))}
            </div>
          </div>

          <div className="h-0.5 w-full bg-white/5">
            <div className="scene scene-progress h-full bg-brand-500" />
          </div>
        </div>

        <div className="scene scene-file absolute left-1/2 top-1/2 w-44 -translate-x-1/2 -translate-y-1/2 rounded-lg border border-line bg-surface p-3.5 shadow-[0_20px_50px_-12px_rgba(0,0,0,0.95)] sm:w-52">
          <div className="mb-3 flex items-center gap-2">
            <UploadIcon className="h-4 w-4 shrink-0 text-brand-500" />
            <span className="truncate text-[11px] text-mute">landing-page.html</span>
          </div>
          <div className="space-y-1.5">
            <div className="h-1.5 w-full rounded-full bg-white/10" />
            <div className="h-1.5 w-2/3 rounded-full bg-white/10" />
          </div>
        </div>

        <div className="scene scene-copied absolute -top-5 right-4 whitespace-nowrap rounded-full border border-brand-500/40 bg-brand-500/15 px-3 py-1 text-[11px] font-medium text-brand-500">
          {dict.copyLink.copied}
        </div>

        <div className="scene scene-views absolute -bottom-6 -left-4 flex items-center gap-2.5 rounded-xl border border-line bg-surface/95 px-3.5 py-2.5 shadow-lg backdrop-blur-sm sm:-left-14">
          <EyeIcon />
          <span className="block h-5 overflow-hidden">
            <span className="scene scene-count block">
              {["12", "128", "742", "1.248"].map((n) => (
                <span key={n} className="block h-5 text-sm font-medium leading-5 tabular-nums">
                  {n}
                </span>
              ))}
            </span>
          </span>
        </div>

        <div className="scene scene-share absolute -right-4 top-1/4 flex items-center gap-2.5 rounded-xl border border-line bg-surface/95 px-3.5 py-2.5 shadow-lg backdrop-blur-sm sm:-right-14">
          <ShareLinkIcon className="h-4 w-4 shrink-0 text-brand-500" />
          <span className="flex -space-x-2">
            {avatars.map(({ tone, label, cls }) => (
              <span
                key={label}
                className={`${cls} flex h-5 w-5 items-center justify-center rounded-full border border-surface text-[9px] font-semibold ${tone}`}
              >
                {label}
              </span>
            ))}
          </span>
        </div>

        <div className="scene scene-comment absolute -bottom-9 right-2 flex max-w-[210px] items-start gap-2.5 rounded-xl border border-line bg-surface/95 px-3.5 py-2.5 shadow-lg backdrop-blur-sm sm:-right-8">
          <CollaborateIcon className="h-4 w-4 shrink-0 text-brand-500" />
          <span className="min-w-0 space-y-1.5 pt-0.5">
            <span className="block h-1.5 w-24 rounded-full bg-white/20" />
            <span className="block h-1.5 w-16 rounded-full bg-white/10" />
          </span>
        </div>
      </div>
    </div>
  );
}



function EyeIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      className="h-3.5 w-3.5 text-brand-500"
    >
      <path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12Z" />
      <circle cx="12" cy="12" r="2.75" />
    </svg>
  );
}
